services:
  backend:
    build:
      context: backend
    container_name: backend
    working_dir: /usr/src/app
    networks:
      - backend-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - '3000:3000'
    command: yarn run start
    depends_on:
      - database

  frontend:
    build:
      context: frontend
    container_name: frontend
    working_dir: /usr/src/app
    networks:
      - backend-network
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - '5173:5173'
    command: yarn run dev

  database:
    image: postgres
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    networks:
      - backend-network

  server:
    build:
      context: server
    container_name: server
    restart: always
    tty: true
    ports:
      - '8000:80'
    networks:
      - backend-network
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - database
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
